### ISSUE TITLE
Text Properties Missing

### ISSUE THREAD

**Issue by Vortelf** [painty/CSS-Used-ChromeExt#14]
1. The url of page inspected.

`every page`

2. The element inspected.

`any text`

3. Expected result.

```css
.someoelement{font-size: Xpx; font-family: XXXX;} //etc.
```
Properties missing

4. Actual result.

```css
.someoelement{}
```
