### ISSUE TITLE
Font family not being set on text

### ISSUE THREAD

**Issue by Acidic9** [painty/CSS-Used-ChromeExt#17]
**The url of page inspected.**

`https://www.faceit.com/en/home`

**The element inspected.**

`body > div:nth-child(2)`

_or_

`<div ui-view="header">...</div>`

**Expected result.**

```css
.text-light {
    font-family: Play, sans-serif;
}
```

**Actual result.**

```css
.text-light {
    font-family: "Times New Roman";
}
```
