### ISSUE TITLE
Using relative URLs

### ISSUE THREAD

**Issue by tibezh** [painty/CSS-Used-ChromeExt#31]
1. The url of page inspected.

Any page where CSS includes fonts, images, etc.
For example https://www.drupal.org/

2. The element inspected.

`ul li.expanded`

3. Expected result.

```css
ul li.expanded{
  list-style-image:url(/misc/menu-expanded.png);
  list-style-type:circle;
}
```

4. Actual result.

```css
ul li.expanded{
  list-style-image:url(https://www.drupal.org/misc/menu-expanded.png);
  list-style-type:circle;
}
```

__________________

As a variant, we can have an option like "Use relative paths only" or smth like this.
