### ISSUE TITLE
Doesn't handle CSS variables

### ISSUE THREAD

**Issue by easrng** [painty/CSS-Used-ChromeExt#39]
# Description
On any page that uses CSS variables CSS Used fails to copy the variable definitions.

# Expected result.
CSS Used copies the CSS variables
```css
:root{--color:#333;}div.somediv{color:var(--color);}
```

# Actual result.

```css
div.somediv{color:var(--color);}
```
